name: forecasting_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pandas>=2.0
  - numpy>=1.25
  - scikit-learn>=1.2
  - lightgbm>=4.0
  - mlflow>=2.7
  - joblib>=1.3
  - matplotlib>=3.8
  - seaborn>=0.12
  - xgboost
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pip
  - pip:
      - optuna>=3.0
      - holidays>=0.27